# Generated by Django 3.2.23 on 2024-01-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0091_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='doc_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
