# Generated by Django 3.2.23 on 2024-01-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0092_summary_doc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='doc_id',
        ),
    ]
